version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - db-network

  pgadmin:
    image: dpage/
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: yakukhno.maria@lll.kpi.ua
      PGADMIN_DEFAULT_PASSWORD: bank123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8088:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - db-network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  db-network:
    driver: bridge
